version: '3.8'
services:
  db:
    container_name: kolesa-db
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "5434:5432"
    volumes:
    - database-data:/var/lib/postgresql/data/
volumes:
  database-data: